version: '2'

# Default (development) configuration
# with dynamic port bindings for parallel execution
#
# docker-compose up

services:
  app:
    build: .
    volumes:
      - .:/opt/tvarkau-vilniu
    ports:
      - "3000:3000"
    links:
      - db
    environment:
      RAILS_ENV: development
      TVARKAU_VILNIU_DB_HOST: db
      TVARKAU_VILNIU_DB_PORT: 3306
    entrypoint: ./wait-for-it.sh db:3306 -t 60 -- ./docker-entrypoint.sh
    volumes:
      - box:/box
  db:
    image: mysql:5.7.20
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: tvarkau_miesta_development
      MYSQL_ROOT_PASSWORD: a
    volumes:
      - mysql-data:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d

volumes:
  mysql-data:
    driver: local
  box:
    driver: local
